# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  argos_config = debug

else ifeq ($(config),release)
  argos_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := argos

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

argos:
ifneq (,$(argos_config))
	@echo "==== Building argos ($(argos_config)) ===="
	@${MAKE} --no-print-directory -C . -f argos.make config=$(argos_config)
	@mkdir -p release
	@cp -f bin/Release/argos release/
endif

clean:
	@${MAKE} --no-print-directory -C . -f argos.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   argos"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"
